import {
  AppShell,
  Button,
  Header,
  Navbar,
  Text,
  MediaQuery,
  Footer,
  Burger,
  Title,
} from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

const Home: NextPage = () => {
  const [opened, setOpened] = useState(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding={0}
        navbarOffsetBreakpoint="sm"
        fixed
        navbar={
          <Navbar
            className="p-4 sm:w-72"
            hiddenBreakpoint="sm"
            hidden={!opened}
          >
            <Text>Application Navbar</Text>
          </Navbar>
        }
        footer={
          <Footer className="p-4" height={64}>
            Application footer
          </Footer>
        }
        header={
          <Header height={72}>
            <div className="flex items-center h-full p-4">
              <MediaQuery largerThan="sm" styles={{ display: "none" }}>
                <Burger
                  opened={opened}
                  onClick={() => setOpened((o) => !o)}
                  size="sm"
                  color={"#71717a"}
                  mr="xl"
                />
              </MediaQuery>
              <Text>Share your ride</Text>
            </div>
          </Header>
        }
      >
        <div className="flex flex-col h-full">
          {/* Next image width and height are ratios of the image dimensions.
          Use responsive in conjunction with cover */}
          <Image
            src="/carpool-friends.svg"
            width={16}
            height={9}
            layout="responsive"
            objectFit="cover"
          />
          <div className="p-4 space-y-4">
            <Title order={1} className="text-ferra">
              ShareRide - Share your ride with others
            </Title>
            <Text>Start by sharing your rides with others</Text>
          </div>
        </div>
      </AppShell>
    </div>
  );
};

export default Home;
